## 선형 회귀

### 1. 데이터 이해

- 훈련 데이터셋, 테스트 데이터셋
    - 데이터 : 파이토치 텐서의 형태 필요(torch.tensor)

![](https://wikidocs.net/images/page/53560/tensor1.PNG)

In [2]:
import torch

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

### 2. 가설수립
- y = W * x + b
    - W : 가중치 / b : 편향

### 3. 비용함수
- 비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)
    - MSE : 평균 제곱 오차(Mean Squared Error)
    - 비용함수를 최소가 되게 만드는 가중치와 편향을 구함

### 4. 경사하강법(Gradient Descent)
    - 옵티마이저(최적화) 알고리즘 
    - W와 b를 찾아가는 과정 : 학습

![](https://wikidocs.net/images/page/21670/%EA%B2%BD%EC%82%AC%ED%95%98%EA%B0%95%EB%B2%95.PNG)

![](https://wikidocs.net/images/page/21670/%EC%A0%91%EC%84%A0%EC%9D%98%EA%B8%B0%EC%9A%B8%EA%B8%B01.PNG)

## 파이토치로 선형회귀 구현

In [3]:
import torch
import torch.nn as nn            # 신경망
import torch.nn.functional as F 
import torch.optim as optim      # 최적화

In [4]:
# 랜덤시드 
torch.manual_seed(1)

### 1. 데이터셋

In [5]:
# 데이터셋

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### 2. 가중치 및 편향 초기화
- zeros > 0
- requires_grad=True : 학습을 통해 값이 변경되는 변수 의미

In [8]:
W = torch.zeros(1, requires_grad=True)  
print(W)

tensor([0.], requires_grad=True)


In [9]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### 3. 가설세우기

In [10]:
hypothesis = x_train * W + b

# test : 0 * x + 0
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 4. 비용함수 선언

In [11]:
cost = torch.mean((hypothesis - y_train)**2) # 오차 제곱의 평균

print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [12]:
optimizer = optim.SGD([W, b], lr=0.01) # SGD
# 학습 대상인 W와 b가 SGD의 입력이 됨.

In [13]:
optimizer.zero_grad() # 기울기 초기화
cost.backward()       # gradient 계산
optimizer.step()      # 업데이트 (경사하강법 적용)

In [14]:
W

tensor([0.1867], requires_grad=True)

### 전체코드

- 에포크(Epoch) : 전체 훈련 데이터가 학습에 한 번 사용된 주기

In [15]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# W 및 b 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)  # SGD

num_epochs = 2000  # 횟수
for epoch in range(num_epochs+1):
  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
  cost.backward()       # 비용 함수를 미분하여 gradient 계산
  optimizer.step()      #위 backward를 통해 x - x*lr 로 경사하강법 실행
    
  # 100번마다 로그 출력
  if epoch % 100 == 0:
      print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
          epoch, num_epochs, W.item(), b.item(), cost.item()
      ))
      

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

- 루프 - 프로세스를 생각해보자

In [25]:
# 초기설정
    # 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

    # W 및 b 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

    # optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)  # SGD로 업데이트

In [26]:
# 가중치 및 편향
print(W, b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


In [27]:
# 순전파
    # H(x) 계산
hypothesis = x_train * W + b

    # cost 계산
cost = torch.mean((hypothesis - y_train) ** 2)

print(hypothesis, cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>) tensor(18.6667, grad_fn=<MeanBackward0>)


In [28]:
# 역전파
optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
cost.backward()       # 비용 함수를 미분하여 gradient 계산
optimizer.step()      #위 backward를 통해 x - x*lr 로 경사하강법 실행

In [29]:
# 가중치 및 편향
print(W, b)

tensor([0.1867], requires_grad=True) tensor([0.0800], requires_grad=True)


In [30]:
# 순전파
    # H(x) 계산
hypothesis = x_train * W + b

    # cost 계산
cost = torch.mean((hypothesis - y_train) ** 2)

print(hypothesis, cost)

tensor([[0.2667],
        [0.4533],
        [0.6400]], grad_fn=<AddBackward0>) tensor(14.7710, grad_fn=<MeanBackward0>)


In [22]:
# 역전파
optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
cost.backward()       # 비용 함수를 미분하여 gradient 계산
optimizer.step()      #위 backward를 통해 x - x*lr 로 경사하강법 실행

In [23]:
# 가중치 및 편향
print(W, b)

tensor([0.3527], requires_grad=True) tensor([0.1509], requires_grad=True)


In [31]:
# 만약 : optimizer.zero_grad() 없다면 미분값이 누적됨

# optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
cost.backward()       # 비용 함수를 미분하여 gradient 계산
optimizer.step()      #위 backward를 통해 x - x*lr 로 경사하강법 실행

# 가중치 및 편향
print(W, b)

tensor([0.5394], requires_grad=True) tensor([0.2309], requires_grad=True)


### optimizer.zero_grad() 

- 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적

In [32]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w  

  z.backward()  # z를 w에 대해 미분하여 gradient 계산 : 미분값 2
  
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


### torch.manual_seed()

In [33]:
torch.manual_seed(5)
torch.rand(1)

tensor([0.8303])

## 자동 미분(Autograd)
- requires_grad=True, backward()
- 자동 미분 > 미분 계산을 자동화하여 경사 하강법을 손쉽게 사용

In [34]:
import torch

- required_grad를 True로 설정
    - 텐서에 대한 기울기를 저장하겠다는 의미
    - w.grad에 w에 대한 미분값이 저장

In [35]:
w = torch.tensor(2.0, requires_grad=True)

In [36]:
# 수식
y = w**2
z = 2*y + 5  # > w에 대해 미분

In [37]:
z.backward()  # z의 w에 대한 미분(기울기) 계산

In [38]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))  
# 4 * 2.0

수식을 w로 미분한 값 : 8.0


## 다중 선형 회귀

- H(x) = w1x1 + w2x2 + w3x3 + b

In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [40]:
torch.manual_seed(1)

### 데이터

In [41]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [42]:
# 가중치도 3개, 편항 1개
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [45]:
w1.item()

0.0

### 코드

In [46]:
# 경사하강법 적용

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5) # 0.00001 # 옵티마이저
num_epochs = 1000 # 반복 횟수

for epoch in range(num_epochs + 1):
    
    # 가설
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b 
    # 비용함수(MES)
    cost = torch.mean((hypothesis - y_train)**2)

    # 역전파
    optimizer.zero_grad()  # 초기화
    cost.backward()  # 미분계산 [w1, w2, w3, b]
    optimizer.step()  # 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
          epoch, num_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
      ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


- 참고
![](image/matmul.png)

### 코드개선

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_train)
print(y_train)

torch.Size([5, 3])
torch.Size([5, 1])
tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  80.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [ ]:
w = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
hypothesis = x_train.matmul(w) + b

In [ ]:
optimizer = optim.SGD([w, b], lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(w) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## nn.Module로 구현하는 선형 회귀
* 이전 까진 가설함수 / 비용함수를 직접 정의해서 구현했찌만, 파이토치 모델을 이용해서 쉽게 구현이 가능함

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
model = nn.Linear(1,1)

In [ ]:
print(list(model.parameters()))
# 첫번째 값이 W / 두번째 값이 b => 두 값모두 랜덤으로 초기화 되어있음.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
num_epochs = 2000
for epoch in range(num_epochs+1):
  pred = model(x_train)
  cost =F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
new_var = torch.FloatTensor([4])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([7.9989], grad_fn=<AddBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831834
Epoch  600/2000 Cost: 4.585997
Epoch  700/2000 Cost: 4.353045
Epoch  800/2000 Cost: 4.132426
Epoch  900/2000 Cost: 3.923438
Epoch 1000/2000 Cost: 3.725488
Epoch 1100/2000 Cost: 3.537972
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192076
Epoch 1400/2000 Cost: 3.032686
Epoch 1500/2000 Cost: 2.881703
Epoch 1600/2000 Cost: 2.738666
Epoch 1700/2000 Cost: 2.603199
Epoch 1800/2000 Cost: 2.474860
Epoch 1900/2000 Cost: 2.353289
Epoch 2000/2000 Cost: 2.238115


In [ ]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7184]], grad_fn=<AddmmBackward>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


## 클래스로 파이토치 모델 구현하기

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim 

In [3]:
model = nn.Linear(1,1)

In [4]:
# 모델 구현 형식 숙지

class LinearRegressionModel(nn.Module):  # 상속
  def __init__(self):  # 초기화
    super().__init__() # nn.Module의 속성 상속
    self.linear = nn.Linear(1, 1)  # 모델 정의

  def forward(self, x): # forward
    return self.linear(x)

In [5]:
model = LinearRegressionModel()

In [6]:
model = nn.Linear(3, 1)

In [7]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [8]:
model = MultivariateLinearRegressionModel()

In [43]:
torch.manual_seed(1)

- 달라진 점은 클래스로 구현했다는 점

In [10]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [11]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

In [12]:
model = LinearRegressionModel()

In [15]:
# 옵티마이저 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [16]:
# 에포크 2000번
num_epochs = 2000
for epoch in range(num_epochs + 1):
    
    # 순전파
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    # 역전파
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print("Epoch {:4d}/{} Cost:{:6f}".format(epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost:13.103541
Epoch  100/2000 Cost:0.002791
Epoch  200/2000 Cost:0.001724
Epoch  300/2000 Cost:0.001066
Epoch  400/2000 Cost:0.000658
Epoch  500/2000 Cost:0.000407
Epoch  600/2000 Cost:0.000251
Epoch  700/2000 Cost:0.000155
Epoch  800/2000 Cost:0.000096
Epoch  900/2000 Cost:0.000059
Epoch 1000/2000 Cost:0.000037
Epoch 1100/2000 Cost:0.000023
Epoch 1200/2000 Cost:0.000014
Epoch 1300/2000 Cost:0.000009
Epoch 1400/2000 Cost:0.000005
Epoch 1500/2000 Cost:0.000003
Epoch 1600/2000 Cost:0.000002
Epoch 1700/2000 Cost:0.000001
Epoch 1800/2000 Cost:0.000001
Epoch 1900/2000 Cost:0.000000
Epoch 2000/2000 Cost:0.000000


In [17]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [18]:
# 클래스 정의
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [19]:
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [20]:
num_epochs = 2000
for epoch in range(num_epochs + 1):

    # 순전파
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    # 역전파
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print("Epoch {:4d}/{} Cost:{:6f}".format(epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost:42134.707031
Epoch  100/2000 Cost:5.960053
Epoch  200/2000 Cost:5.654707
Epoch  300/2000 Cost:5.365413
Epoch  400/2000 Cost:5.091429
Epoch  500/2000 Cost:4.831834
Epoch  600/2000 Cost:4.585997
Epoch  700/2000 Cost:4.353075
Epoch  800/2000 Cost:4.132411
Epoch  900/2000 Cost:3.923455
Epoch 1000/2000 Cost:3.725502
Epoch 1100/2000 Cost:3.537972
Epoch 1200/2000 Cost:3.360326
Epoch 1300/2000 Cost:3.192056
Epoch 1400/2000 Cost:3.032674
Epoch 1500/2000 Cost:2.881700
Epoch 1600/2000 Cost:2.738672
Epoch 1700/2000 Cost:2.603201
Epoch 1800/2000 Cost:2.474846
Epoch 1900/2000 Cost:2.353286
Epoch 2000/2000 Cost:2.238110


## 미니 배치와 데이터 로드
- 데이터가 수십만개 이상이라면,
    - 전체 데이터에 대해서 경사 하강법을 수행하는 것은 매우 느림(메모리 소요)
- 데이터를 작은 단위로 나눠 해당 단위로 학습 : 미니배치 경사하강법
    - 미니 배치만큼 비용(cost)를 계산하고 경사하강법
        - 전체가 다 끝나면 1 에포크(동일개념)
    - 미니 배치의 크기 : batch size(보통 2의 제곱수 활용)
    - 전체 데이터의 일부만을 보고 수행
    - 최적값으로 수렴하는 과정에서 값이 조금 헤맴, 훈련 속도는 빠름
    
![](https://wikidocs.net/images/page/55580/%EB%AF%B8%EB%8B%88%EB%B0%B0%EC%B9%98.PNG)

- 이터레이션
    - 파라미터 업데이트 횟수 
        - total data / batch size
        
![](https://wikidocs.net/images/page/36033/batchandepochiteration.PNG)

### 데이터로드
- 데이터셋(Dataset)과 데이터로더(DataLoader)를 제공

In [61]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [62]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [63]:
torch.manual_seed(1)

In [64]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [65]:
# TensorDataset
dataset = TensorDataset(x_train, y_train) # TensorDataset : 턴서를 입력으로

In [71]:
dataset

In [66]:
# batch_size, shuffle :에포크마다 데이터 섞음 (True 권장)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [59]:
# 모델정의
model = nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [67]:
# 클래스 정의
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [68]:
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [69]:
num_epochs = 20
for epoch in range(num_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
    
        # print(batch_idx)
        # print(samples)    

        # 미니배치
        x_train, y_train = samples 
        # 순전파  
        pred = model(x_train)
        cost = F.mse_loss(pred, y_train)

        # 역전파
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, num_epochs, batch_idx+1, len(dataloader),
            cost.item()))

Epoch    0/20 Batch 1/3 Cost: 23071.781250
Epoch    0/20 Batch 2/3 Cost: 17581.359375
Epoch    0/20 Batch 3/3 Cost: 3703.553467
Epoch    1/20 Batch 1/3 Cost: 857.132324
Epoch    1/20 Batch 2/3 Cost: 194.912857
Epoch    1/20 Batch 3/3 Cost: 103.150658
Epoch    2/20 Batch 1/3 Cost: 16.461069
Epoch    2/20 Batch 2/3 Cost: 10.970690
Epoch    2/20 Batch 3/3 Cost: 2.953053
Epoch    3/20 Batch 1/3 Cost: 1.246350
Epoch    3/20 Batch 2/3 Cost: 0.095024
Epoch    3/20 Batch 3/3 Cost: 0.104377
Epoch    4/20 Batch 1/3 Cost: 0.678422
Epoch    4/20 Batch 2/3 Cost: 0.123370
Epoch    4/20 Batch 3/3 Cost: 0.118070
Epoch    5/20 Batch 1/3 Cost: 0.094797
Epoch    5/20 Batch 2/3 Cost: 0.531496
Epoch    5/20 Batch 3/3 Cost: 0.011198
Epoch    6/20 Batch 1/3 Cost: 0.219984
Epoch    6/20 Batch 2/3 Cost: 0.042412
Epoch    6/20 Batch 3/3 Cost: 0.917457
Epoch    7/20 Batch 1/3 Cost: 0.213805
Epoch    7/20 Batch 2/3 Cost: 0.640249
Epoch    7/20 Batch 3/3 Cost: 0.005267
Epoch    8/20 Batch 1/3 Cost: 0.454904
Epoch 

In [70]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred = model.forward(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.0829]], grad_fn=<AddmmBackward0>)


## 커스텀 데이터셋
-기본적인 파이토치 구조 : Dataset > DataLoader

In [79]:
import torch
import torch.nn.functional as F

In [80]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [81]:
torch.manual_seed(1)

In [82]:
# 기본적 뼈대
class CustomDataset(torch.utils.data.Dataset):  # 상속
  def __init__(self):  # 초기화
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx]) # 인덱싱
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [83]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [84]:
# model = torch.nn.Linear(3, 1)
# optimizer = optim.SGD(model.parameters(), lr=1e-5)

model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [85]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
        x_train, y_train = samples

        # H(x) 계산
        prediction = model(x_train)
        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
            ))

Epoch    0/20 Batch 1/3 Cost: 23071.781250
Epoch    0/20 Batch 2/3 Cost: 17581.359375
Epoch    0/20 Batch 3/3 Cost: 3703.553467
Epoch    1/20 Batch 1/3 Cost: 857.132324
Epoch    1/20 Batch 2/3 Cost: 194.912857
Epoch    1/20 Batch 3/3 Cost: 103.150658
Epoch    2/20 Batch 1/3 Cost: 16.461069
Epoch    2/20 Batch 2/3 Cost: 10.970690
Epoch    2/20 Batch 3/3 Cost: 2.953053
Epoch    3/20 Batch 1/3 Cost: 1.246350
Epoch    3/20 Batch 2/3 Cost: 0.095024
Epoch    3/20 Batch 3/3 Cost: 0.104377
Epoch    4/20 Batch 1/3 Cost: 0.678422
Epoch    4/20 Batch 2/3 Cost: 0.123370
Epoch    4/20 Batch 3/3 Cost: 0.118070
Epoch    5/20 Batch 1/3 Cost: 0.094797
Epoch    5/20 Batch 2/3 Cost: 0.531496
Epoch    5/20 Batch 3/3 Cost: 0.011198
Epoch    6/20 Batch 1/3 Cost: 0.219984
Epoch    6/20 Batch 2/3 Cost: 0.042412
Epoch    6/20 Batch 3/3 Cost: 0.917457
Epoch    7/20 Batch 1/3 Cost: 0.213805
Epoch    7/20 Batch 2/3 Cost: 0.640249
Epoch    7/20 Batch 3/3 Cost: 0.005267
Epoch    8/20 Batch 1/3 Cost: 0.454904
Epoch 

In [86]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.0829]], grad_fn=<AddmmBackward0>)
